#!/usr/bin/env bash
# 5agents on Hugging Face Spaces — エントリポイント
#
# 役割:
#   1. /data (Persistent Storage) のサブディレクトリを用意して書き込み権限を確保
#   2. SQLite / ChromaDB 用パスを export
#   3. supervisord を foreground で起動 (PID 1)
#
# HF Spaces の挙動メモ:
#   - Persistent Storage を有効にすると /data がマウントされ、再起動後もファイルが残る
#   - 無効の場合は /tmp/data に書き出すフォールバック (再起動でロスト)

set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*"; }

# ───────── 永続化ディレクトリ ─────────
# Persistent Storage 有効 → /data が書き込み可
# 無効                   → /tmp/data に逃がす
if [ -w /data ]; then
    DATA_DIR=/data
    log "Persistent Storage 検出: /data を使用"
else
    DATA_DIR=/tmp/data
    log "/data は書き込み不可。/tmp/data にフォールバック (再起動でロスト)"
fi

mkdir -p "$DATA_DIR/chroma_db"
mkdir -p "$DATA_DIR/logs"

# config.py が参照する環境変数として export
export DATA_DIR
export CHROMA_PERSIST_DIR="$DATA_DIR/chroma_db"
export SQLITE_PATH="$DATA_DIR/runs.sqlite"

log "DATA_DIR=$DATA_DIR"
log "CHROMA_PERSIST_DIR=$CHROMA_PERSIST_DIR"
log "SQLITE_PATH=$SQLITE_PATH"

# ───────── /tmp の nginx 用ディレクトリ ─────────
mkdir -p /tmp/nginx-client-body /tmp/nginx-proxy /tmp/nginx-fastcgi /tmp/nginx-uwsgi /tmp/nginx-scgi

# ───────── Phase 5 Theme C: Streamlit OIDC auth secrets.toml 生成 ─────────
# HF Spaces が hf_oauth: true 設定で OAUTH_CLIENT_ID/SECRET と OPENID_PROVIDER_URL を
# 環境変数として注入する。Streamlit のネイティブ OIDC auth (st.login / st.user) を使うには
# .streamlit/secrets.toml に [auth] セクションが必要。コミットには含められない値なので
# 起動時に env から動的生成する。
if [ -n "${OAUTH_CLIENT_ID:-}" ] && [ -n "${OAUTH_CLIENT_SECRET:-}" ] && [ -n "${SPACE_HOST:-}" ]; then
    mkdir -p /app/.streamlit
    # cookie_secret: 長期セッション署名用。OAUTH_CLIENT_SECRET を再利用 (HF が定期再生成).
    cat > /app/.streamlit/secrets.toml <<SECRETS_EOF
# Auto-generated by entrypoint.sh. Do NOT commit.
[auth]
redirect_uri = "https://${SPACE_HOST}/oauth2callback"
cookie_secret = "${OAUTH_CLIENT_SECRET}"
client_id = "${OAUTH_CLIENT_ID}"
client_secret = "${OAUTH_CLIENT_SECRET}"
server_metadata_url = "${OPENID_PROVIDER_URL:-https://huggingface.co}/.well-known/openid-configuration"
client_kwargs = { scope = "openid profile" }
SECRETS_EOF
    chmod 600 /app/.streamlit/secrets.toml
    log "Streamlit OIDC secrets.toml を生成しました (host=${SPACE_HOST})"
else
    log "HF OAuth env が未設定 — Streamlit auth は無効モード (ローカル開発 or OAuth 未有効)"
fi

# ───────── Phase 5 Theme C: 初期 admin を allowed_users に投入 ─────────
# INITIAL_ADMIN_HF_USERNAME が設定されていれば、その HF username を admin として登録する.
# 既に存在する場合は何もしない (誤って role を上書きしないため).
if [ -n "${INITIAL_ADMIN_HF_USERNAME:-}" ]; then
    /app/.venv/bin/python -c "
from src.memory.logger import RunLogger
RunLogger().ensure_admin('${INITIAL_ADMIN_HF_USERNAME}')
print('initial admin ensured: ${INITIAL_ADMIN_HF_USERNAME}')
" 2>&1 || log "ensure_admin 失敗 (DB 未準備の可能性、起動時に再試行されます)"
else
    log "INITIAL_ADMIN_HF_USERNAME 未設定 — 初期 admin 登録をスキップ"
fi

# ───────── 必須環境変数の sanity check (Secrets 設定漏れの早期検知) ─────────
missing=()
for key in GOOGLE_API_KEY GROQ_API_KEY TAVILY_API_KEY; do
    if [ -z "${!key:-}" ]; then
        missing+=("$key")
    fi
done
if [ ${#missing[@]} -gt 0 ]; then
    log "⚠️  以下の Secrets が未設定です: ${missing[*]}"
    log "    HF Space の Settings → Variables and secrets で追加してください"
fi

# LINE は任意 (UI だけ使う場合は未設定でも起動できる)
if [ -z "${LINE_CHANNEL_SECRET:-}" ] || [ -z "${LINE_CHANNEL_ACCESS_TOKEN:-}" ]; then
    log "ℹ️  LINE_CHANNEL_SECRET/ACCESS_TOKEN 未設定 (LINE 連携を使わないなら無視)"
fi

# Phase 5 Theme C: HF OAuth + admin の sanity check
if [ -z "${OAUTH_CLIENT_ID:-}" ]; then
    log "ℹ️  OAUTH_CLIENT_ID 未注入 — HF Space README で hf_oauth: true を有効化してください"
fi
if [ -z "${INITIAL_ADMIN_HF_USERNAME:-}" ]; then
    log "⚠️  INITIAL_ADMIN_HF_USERNAME 未設定 — 初期 admin が登録されず管理画面に入れません"
fi

# 旧 STREAMLIT_PASSWORD は廃止 (HF OAuth に移行)
if [ -n "${STREAMLIT_PASSWORD:-}" ]; then
    log "ℹ️  STREAMLIT_PASSWORD は Phase 5.C 以降廃止されました (HF OAuth で置換) — Secret 削除推奨"
fi

# ───────── supervisord 起動 ─────────
log "supervisord を起動..."
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
